language: python
dist: bionic
python:
  - "3.7"

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .[tests]

script:
  - python -m pytest -ra

deploy:
  provider: pypi
  edge: true
  distributions: sdist bdist_wheel
  username: $PYPI_USER
  password: $PYPI_PW
  on:
    tags: true
