language: python
dist: bionic
python:
  - "3.7"

services:
  - docker

install:
  - docker run -d -it --name tbears-container -p 9000:9000 iconloop/tbears:mainnet

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: $PYPI_USER
  password: $PYPI_PW
  on:
    tags: true
